/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Extract project ID from full URL or use hardcoded fallback
const supabaseUrl = import.meta.env?.VITE_SUPABASE_URL || "https://uokjpidaphfcgzmjolvf.supabase.co";
const projectIdFromUrl = supabaseUrl.replace('https://', '').replace('.supabase.co', '');

export const projectId = projectIdFromUrl || "uokjpidaphfcgzmjolvf";
export const publicAnonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVva2pwaWRhcGhmY2d6bWpvbHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1OTY5ODMsImV4cCI6MjA4NDE3Mjk4M30.xdTzKjA4fVpGnnsC6Xf2KHB3xhB4SLG7TqHzyJygX-Y";